<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="4" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="83" started-at="2015-08-13T03:32:01Z" finished-at="2015-08-13T03:32:01Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="83" started-at="2015-08-13T03:32:01Z" finished-at="2015-08-13T03:32:01Z">
      <class name="com.hedwig.ut.samples.simpleMethod.DateUtilsTest">
        <test-method status="PASS" signature="secondJuneWasSunday()[pri:0, instance:com.hedwig.ut.samples.simpleMethod.DateUtilsTest@76a4d6c]" name="secondJuneWasSunday" duration-ms="51" started-at="2015-08-13T11:32:01Z" finished-at="2015-08-13T11:32:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- secondJuneWasSunday -->
        <test-method status="PASS" signature="tenthAprilWasWednesday()[pri:0, instance:com.hedwig.ut.samples.simpleMethod.DateUtilsTest@76a4d6c]" name="tenthAprilWasWednesday" duration-ms="1" started-at="2015-08-13T11:32:01Z" finished-at="2015-08-13T11:32:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tenthAprilWasWednesday -->
        <test-method status="PASS" signature="thirdMayWasFriday()[pri:0, instance:com.hedwig.ut.samples.simpleMethod.DateUtilsTest@76a4d6c]" name="thirdMayWasFriday" duration-ms="0" started-at="2015-08-13T11:32:01Z" finished-at="2015-08-13T11:32:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirdMayWasFriday -->
      </class> <!-- com.hedwig.ut.samples.simpleMethod.DateUtilsTest -->
      <class name="com.hedwig.ut.samples.simpleMethod.ExceptionTest">
        <test-method status="PASS" signature="expectingException()[pri:0, instance:com.hedwig.ut.samples.simpleMethod.ExceptionTest@1f021e6c]" name="expectingException" duration-ms="1" started-at="2015-08-13T11:32:01Z" finished-at="2015-08-13T11:32:01Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[ah error occurred!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: ah error occurred!
	at com.hedwig.ut.samples.simpleMethod.ExceptionTest$MyExceptionInvoker.pretendToDoSth(ExceptionTest.java:18)
	at com.hedwig.ut.samples.simpleMethod.ExceptionTest.expectingException(ExceptionTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at com.hedwig.ut.samples.simpleMethod.Main.main(Main.java:13)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- expectingException -->
      </class> <!-- com.hedwig.ut.samples.simpleMethod.ExceptionTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
